/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type BrineDB = BrineDb
export class BrineDb {
  connectionUri: string
  constructor(connectionUri: string)
  connect(): Promise<boolean>
  migrate(): Promise<void>
  get(key: string): Promise<string | null>
  set(key: string, value: string): Promise<void>
  setMany(data: Array<[string, string]>): Promise<void>
  getMany(keys: Array<string>): Promise<Record<string, string | undefined | null>>
  clear(): Promise<void>
  delete(key: string): Promise<void>
  deleteMany(keys: Array<string>): Promise<void>
  keys(): Promise<Array<string>>
  values(): Promise<Array<string>>
  count(): Promise<number>
  has(key: string): Promise<boolean>
  close(): Promise<void>
}
