[package]
name = "brinedb-entity"
version = "1.0.0"
license = "MIT"
edition = "2018"

[dependencies]
sea-orm = { version = "1.0.0", features = [
    "runtime-tokio-native-tls",
    "sqlx-mysql",
    "sqlx-postgres",
    "sqlx-sqlite",
    "macros"
] }
