name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node
        uses: josh-development/.github/setup-node@main
        with:
          version: 20

      - name: Select Rust Toolchain
        run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
    
      - name: Run ESLint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
